### ISSUE TITLE
Bug of fmatch algorithm

### ISSUE THREAD

**Issue by Alan-JW** [dem123456789/SemiFL-Semi-Supervised-Federated-Learning-for-Unlabeled-Clients-with-Alternate-Training#1]
Hello @dem123456789 , I encountered such a bug when I ran the fmatch algorithm （python train_classifier_ssfl.py --device 3 --data_name CIFAR10 --model_name wresnet28x2 --control_name 4000_fmatch@0.95_100_0.1_iid_5-5_0.5_1）, what modification should I do?  Thanks for your answer!
![image](https://user-images.githubusercontent.com/74579183/206797156-e1cd43e0-5bfd-482d-ae17-1b6e880b1f32.png)

**Comment by diaoenmao** [comment]
fmatch stands for fedmatch and it only works with decwresnet.
