### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by lhq12** [dem123456789/SemiFL-Semi-Supervised-Federated-Learning-for-Unlabeled-Clients-with-Alternate-Training#2]
https://github.com/dem123456789/SemiFL-Semi-Supervised-Federated-Learning-for-Unlabeled-Clients-with-Alternate-Training/blob/a4fab0a84dd6cfd10bfaa93d9a2cb17ff05e5ed5/src/utils.py#L110
I think this line should be `cfg['data_size'] = {'train': len(dataset['train']), 'test': len(dataset['test'])}`.

**Comment by diaoenmao** [comment]
Yeah. You are correct.

**Comment by lhq12** [comment]
I don't want to bother you, but I haven't been able to figure out the meaning of this function: `def make_batchnorm_stats(dataset, model, tag)` in data.py. Could please help me?
