### ISSUE TITLE
Custom data training

### ISSUE THREAD

**Issue by chillum-codeX** [dem123456789/SemiFL-Semi-Supervised-Federated-Learning-for-Unlabeled-Clients-with-Alternate-Training#3]
How to do model training on custom ct scan images

**Comment by Rumking** [comment]
You would need to:
1.) Implement your own CT_Dataset class in a ct_dataset.py file
2.) Place the ct_dataset.py file in the src/datasets folder. 
3.) Modify the src/data.py file by including your dataset properties (data_stats, data_name, transforms, etc.) where necessary
4.) Try to see if you can make any other changes to other data-related functions.

(Word of advice: If you can, try to avoid using this codebase, as it is quite convoluted and unintuitive. It might take less time implementing the method yourself.)

**Comment by diaoenmao** [comment]
Well, this codebase was adapted from my own [research pipeline](https://github.com/diaoenmao/RPipe) long tine ago. Thanks for helping though.
