### ISSUE TITLE
DIfference of Server.update from other aggregate method of FL?

### ISSUE THREAD

**Issue by bltnynk** [dem123456789/SemiFL-Semi-Supervised-Federated-Learning-for-Unlabeled-Clients-with-Alternate-Training#5]
In the update method of class Server, instead of merely averaging like usual FL algorithm, SemiFL compute the weighted average of weight update and use it as the gradient to update the global model. May I ask the reason for this and any related paper regarding this? I don't think an explanation is provided in the paper.
<img width="671" alt="image" src="https://github.com/diaoenmao/SemiFL-Semi-Supervised-Federated-Learning-for-Unlabeled-Clients-with-Alternate-Training/assets/61192617/11d12855-1a49-4463-ac47-cfaa8075c494">

**Comment by diaoenmao** [comment]
In fact, it is equal weight here. The original fedavg paper used weight based on the local sample size.

**Comment by bltnynk** [comment]
Thanks for your prompt response. However, the more important part that I'm thinking about is the use of global_optimizer, which treat the sum of model's update as the gradient. This seems to be quite a unique way to aggregate client's model weight compare to usual method of simply averaging. So I'm wondering if this is intended and what is the rationale behind that.

Please feel free to answer whenever you have time. Thank you so much for the great work.

**Comment by diaoenmao** [comment]
It is a random thought when I developed this paper. Later I found out it is related to this [work](https://arxiv.org/abs/2003.00295).
