### ISSUE TITLE
FedMatch implementation

### ISSUE THREAD

**Issue by bltnynk** [dem123456789/SemiFL-Semi-Supervised-Federated-Learning-for-Unlabeled-Clients-with-Alternate-Training#6]
In the current SemiFL repo, I only see half of "FedMatch" algorithm was implemented (disjoint learning), while the inter-client consistency  loss (which include agreement-based pseudo label) was not implemented.

May I ask if this is intentional?

**Comment by diaoenmao** [comment]
It does not outperform the 'Partially Supervised' case so I did not spend much time on reproducing their code.
